services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  drizzle-gateway:
    image: ghcr.io/drizzle-team/gateway:latest
    container_name: drizzle-gate
    restart: always
    ports:
      - "4983:4983"
    environment:
      PORT: 4983                # Set the port for Drizzle Gateway (optional)
      STORE_PATH: /app          # Set your store path (optional)
      # MASTERPASS: your_master_password  # Set your master pass (optional)
    volumes:
      - drizzle-gateway:/app

volumes:
  drizzle-gateway:
  pgdata: