/**
 * Database Seed Script
 * 
 * Seeds the database with sample data for development and testing.
 * This script can be run to populate a fresh database with realistic data.
 */

import { eq } from 'drizzle-orm';
import { getDatabase } from '../lib/db';
import { initializeDatabaseConfig } from '../lib/db';
import { createAppConfig } from '../config/types';
import { users, todos } from '../infrastructure/db/schema';

async function seedDatabase() {
  console.log('🌱 Starting database seeding...');

  try {
    // Initialize database configuration
    const appConfig = createAppConfig();
    initializeDatabaseConfig(appConfig.database, appConfig.server.nodeEnv);

    const db = await getDatabase();

    // Check if data already exists
    const existingUsers = await db.select().from(users).limit(1);
    if (existingUsers.length > 0) {
      console.log('🔍 Database already contains data. Skipping seed.');
      return;
    }

    console.log('👤 Creating seed users...');

    // Create seed users (IDs will be auto-generated by database)
    const seedUsers = [
      {
        email: 'john@example.com',
        name: 'John Doe',
        roles: ['user'] as ('admin' | 'user')[],
        isActive: true,
      },
      {
        email: 'admin@example.com',
        name: 'Admin User',
        roles: ['admin', 'user'] as ('admin' | 'user')[],
        isActive: true,
      },
    ];

    const insertedUsers = await db.insert(users).values(seedUsers).returning();
    console.log(`✅ Created ${seedUsers.length} users`);

    const user1 = insertedUsers[0];
    const user2 = insertedUsers[1];

    if (!user1 || !user2) {
      throw new Error('Failed to create required seed users');
    }

    console.log('📝 Creating seed todos...');

    // Create seed todos
    const seedTodos = [
      {
        title: 'Learn Drizzle ORM',
        description: 'Study the documentation and build a sample project',
        completed: false,
        userId: user1.id,
      },
      {
        title: 'Set up PostgreSQL database',
        description: 'Configure local development database',
        completed: true,
        userId: user1.id,
      },
      {
        title: 'Write migration scripts',
        description: 'Create database schema migration files',
        completed: true,
        userId: user1.id,
      },
      {
        title: 'Review user permissions',
        description: 'Audit user access levels and roles',
        completed: false,
        userId: user2.id,
      },
      {
        title: 'Update system documentation',
        description: 'Keep documentation current with latest changes',
        completed: false,
        userId: user2.id,
      },
    ];

    await db.insert(todos).values(seedTodos);
    console.log(`✅ Created ${seedTodos.length} todos`);

    console.log('🎉 Database seeding completed successfully!');
    console.log('\n📊 Seed data summary:');
    console.log(`  - ${seedUsers.length} users created`);
    console.log(`  - ${seedTodos.length} todos created`);
    console.log('\n👥 Test accounts:');
    console.log('  - john@example.com (User)');
    console.log('  - admin@example.com (Admin)');

  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedDatabase().catch((error) => {
    console.error('Fatal seeding error:', error);
    process.exit(1);
  });
}

export { seedDatabase };